#!/usr/bin/env bash
###################
# appinfo
#
#####
# ChangeLog
# ---------
# 2016-12-11  1.1.0      Now calls fileinfo script for basic file info
# 2016-12-10  1.0.0      Initial script creation
#


#
# APP DATA
#
declare -r APP_NAME='AppInfo'
declare -r APP_VERSION='1.1.0'
declare -r APP_LABEL="$APP_NAME v$APP_VERSION"
declare -r CLI_NAME='appinfo'


#
# CONSTANTS
#

declare -r VERSION_REGEX='.*(^| | v|version )(([0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+|\([0-9]+\))?)(-(release|develop|prerelease|pre|patch))?).*$'


#
# VARIABLES
#
declare -i exit_code

app_label=''
app_ver=''


#
# FUNCTIONS
#
debug()
{
	echo "$1" 1>&2
}


get_app_label()
{
	head_line="${1:-1}"
	# debug "head_line: $head_line"
	app_label=$($app_path --version 2> /dev/null | head "-$head_line" | xargs)
	# debug "get_app_label() | x${app_label}x | --version"
	if [[ "x${app_label}x" == 'xx' ]]; then
		app_label=$($app_path -v 2> /dev/null | head "-$head_line" | xargs)
		# debug "get_app_label() | x${app_label}x | -v"
		if [[ "x${app_label}x" == 'xx' ]]; then
			app_label=$($app_path -V 2> /dev/null | head "-$head_line" | xargs)
			# debug "get_app_label() | x${app_label}x | -V"
			if [[ "x${app_label}x" == 'xx' ]]; then
				app_label='unknown'
			fi
		fi
	fi
}


#
# MAIN
#
if [[ $# -eq 0 ]]; then
	echo "$APP_LABEL"
	echo
	echo "Please specify the app name to get info for."
	echo
else
	echo
	for app_path in $(which -a $1); do
		get_app_label
		if [[ "$app_label" = '' ]]; then
			get_app_label 2
		fi

		# app_label='1.2.3(4)-release (x86_64-apple-darwin15.6.0)'

		if [[ "$app_label" =~ $VERSION_REGEX ]]; then
			# echo "\${BASH_REMATCH[*]}: ${BASH_REMATCH[*]}"
			# [[ -n "${BASH_REMATCH[0]}" ]] && echo "\${BASH_REMATCH[0]}: '${BASH_REMATCH[0]}'"
			# [[ -n "${BASH_REMATCH[1]}" ]] && echo "\${BASH_REMATCH[1]}: '${BASH_REMATCH[1]}'"
			# [[ -n "${BASH_REMATCH[2]}" ]] && echo "\${BASH_REMATCH[2]}: '${BASH_REMATCH[2]}'"
			# [[ -n "${BASH_REMATCH[3]}" ]] && echo "\${BASH_REMATCH[3]}: '${BASH_REMATCH[3]}'"
			# [[ -n "${BASH_REMATCH[4]}" ]] && echo "\${BASH_REMATCH[4]}: '${BASH_REMATCH[4]}'"
			# [[ -n "${BASH_REMATCH[5]}" ]] && echo "\${BASH_REMATCH[5]}: '${BASH_REMATCH[5]}'"
			# [[ -n "${BASH_REMATCH[6]}" ]] && echo "\${BASH_REMATCH[6]}: '${BASH_REMATCH[6]}'"
			# [[ -n "${BASH_REMATCH[7]}" ]] && echo "\${BASH_REMATCH[7]}: '${BASH_REMATCH[7]}'"
			# [[ -n "${BASH_REMATCH[8]}" ]] && echo "\${BASH_REMATCH[8]}: '${BASH_REMATCH[8]}'"
			app_ver="${BASH_REMATCH[2]}"
		else
			app_ver=$(echo "$app_label" | rev | cut -d' ' -f1 | rev)
		fi

		echo "  App Label:   $app_label"
		echo "  App Version: $app_ver"
		fileinfo "$app_path" | tail -n +2
	done
fi

